import clsx from "clsx";
import { Metadata } from "next";

export const metadata: Metadata = {
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className={clsx([`sm:p-0`])}>{children}</main>;
}
